---
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

require:
  - rubocop-performance
  - rubocop-rspec

Layout:
  Severity: warning

Layout/LineLength:
  Max: 80

Metrics:
  Severity: warning

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition

Style/PreferredHashMethods:
  EnforcedStyle: verbose
