---
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

plugins:
  - rubocop-performance
  - rubocop-rspec

Layout/LineLength:
  Max: 80
  AllowedPatterns:
    - gemini://

Metrics/BlockLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/ClassLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/ModuleLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

RSpec/ExampleLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition

Style/PreferredHashMethods:
  EnforcedStyle: verbose
